;Carlos Isaac Espinoza Alvarez
;Cibernetica
;Programacion en ensamblador
;Modo grafico nivel pixel iniciales 'CIEA'

MOV AH, 0h			;CONFIGURAR PANTALLA
MOV AL, 13h
INT 10H

MOV AH, 0CH
MOV AL, 1
MOV CX, 40			;CAMBIAR CX DE POSICION
MOV DX, 1			;CAMBIAR DX DE POSICION


LETRAC:				;EMPIEZA LA LETRA 'C'
	DEC CX			;SE INCREMENTA EN HORIZONTAL
	INT 10H
	CMP CX, 1		;COMPARA CX HASTA QUE LA DIFERENCIA SEA '0'
	JZ SAL.C			;BRINCO SI ES CERO
	JMP LETRAC		;BRINCO INCONDICIONAL
SAL.C:
	INC DX			;SE INCREMENTA EN VERTICAL
	INT 10H
	CMP DX, 30		;COMPARA DX HASTA QUE LA DIFERENCIA SEA '0'
	JZ TERMINA.C		;BRINCO SI ES CERO
	JMP SAL.C		;BRINCO INCONDICIONAL
TERMINA.C:
	INC CX			;SE INCREMENTA EN HORIZONTAL
	INT 10H
	CMP CX, 40		;COMPARA CX HASTA QUE LA DIFERENCIA SEA '0'
	JZ FIN.C			;BRINCO SI ES CERO
	JMP TERMINA.C		;BRINCO INCONDICIONAL
FIN.C:

MOV AH, 0CH
MOV AL, 1
MOV CX, 50			;CAMBIAR CX DE POSICION
MOV DX, 1			;CAMBIAR DX DE POSICION


LETRA.I:			;EMPIEZA LA LETRA 'I'

	INC DX			;SE INCREMENTA EN VERTICAL
	INT 10H
	CMP DX, 30		;COMPARA DX HASTA QUE LA DIFERENCIA SEA '0'
	JZ TERMINA.I		;BRINCO SI ES CERO
	JMP LETRA.I		;BRINCO INCONDICIONAL
TERMINA.I:


MOV AH, 0CH
MOV AL, 1
MOV CX, 90			;CAMBIAR CX DE POSICION
MOV DX, 1			;CAMBIAR DX DE POSICION


LETRA.E:				;EMPIEZA LA LETRA 'E'

	DEC CX			;SE INCREMENTA EN HORIZONTAL
	INT 10H
	CMP CX, 60		;COMPARA CX HASTA QUE LA DIFERENCIA SEA '0'
	JZ TERMINA.E		;BRINCO SI ES CERO
	JMP LETRA.E		;BRINCO INCONDICIONAL

TERMINA.E:

	INC DX			;SE INCREMENTA EN VERTICAL
	INT 10H
	CMP DX, 30		;COMPARA DX HASTA QUE LA DIFERENCIA SEA '0'
	JZ SAL.E			;BRINCO SI ES CERO
	JMP TERMINA.E		;BRINCO INCONDICIONAL
SAL.E:
	INC CX			;SE INCREMENTA EN HORIZONTAL
	INT 10H
	CMP CX, 90		;COMPARA CX HASTA QUE LA DIFERENCIA SEA '0'
	JZ FIN.E			;BRINCO SI ES CERO
	JMP SAL.E		;BRINCO INCONDICIONAL
FIN.E:

MOV CX, 60			;CAMBIAR CX DE POSICION
MOV DX, 15			;CAMBIAR DX DE POSICION


LETRA.EE:
	INC CX			;SE INCREMENTA EN HORIZONTAL
	INT 10H
	CMP CX, 75		;COMPARA CX HASTA QUE LA DIFERENCIA SEA '0'
	JZ FIN.EE		;BRINCO SI ES CERO
	JMP LETRA.EE		;BRINCO INCONDICIONAL
FIN.EE:

MOV CX, 130			;CAMBIAR CX DE POSICION
MOV DX, 1			;CAMBIAR DX DE POSICION


LETRA.A:			;EMPIEZA LA LETRA 'A'
	DEC CX
	INC DX			;SE INCREMENTA EN VERTICAL
	INT 10H
	CMP CX, 75		;COMPARA CX HASTA QUE LA DIFERENCIA SEA '0'
	CMP DX, 30		;COMPARA DX HASTA QUE LA DIFERENCIA SEA '0'	
	JZ FIN.A			;BRINCO SI ES CERO
	JMP LETRA.A		;BRINCO INCONDICIONAL
FIN.A:

MOV CX, 130			;CAMBIAR CX DE POSICION
MOV DX, 1			;CAMBIAR DX DE POSICION


LETRA.AA:
	INC CX			;SE INCREMENTA EN HORIZONTAL
	INC DX			;SE INCREMENTA EN VERTICAL
	INT 10H
	CMP CX, 75		;COMPARA CX HASTA QUE LA DIFERENCIA SEA '0'
	CMP DX, 30		;COMPARA DX HASTA QUE LA DIFERENCIA SEA '0'	
	JZ FIN.AA		;BRINCO SI ES CERO
	JMP LETRA.AA		;BRINCO INCONDICIONAL
FIN.AA:

MOV CX, 115			;CAMBIAR CX DE POSICION
MOV DX, 15			;CAMBIAR DX DE POSICION

LETRA.A2:
	INC CX			;SE INCREMENTA EN HORIZONTAL
	INT 10H		
	CMP CX, 144		;COMPARA CX HASTA QUE LA DIFERENCIA SEA '0'
	JZ FINA.A2		;BRINCO SI ES CERO
	JMP LETRA.A2		;BRINCO INCONDICIONAL
FINA.A2:

RET
