;CARLOS ISAAC ESPINOZA ALVAREZ
;EJERCICIO 7 EXAMEN PRIMER PARCIAL
MOV AL, 'H'		;H SERA NUESTRA "BANDERA" DE HABILITADO

OUT INH, AL		;ESTOS REGISTROS SON LOS QUE TOMAN LA BANDERA H EN AL POR LO TANTO ESTAN HABILITADOS
OUT INT, AL		;USAMOS LA INSTRUCCION OUT PARA QUE TENGA DE SALIDA LOS REGISTROS QUE SE PIDEN
OUT MC, AL
OUT RTG, AL
OUT EXT, AL
OUT CONT, AL

MOV AL, 'I'		;CAMBIAMOS EL VALOR DEL REGISTRO DE AL, YA QUE TENERMOS QUE PONER INHABILITADOS CON 'I'

OUT EN, AL		;TODOS ESTOS REGISTROS ESTAN DESHABILITADOS
OUT RIU, AL
OUT P, AL
OUT ALT, AL
RET