# Project: aaaa
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Grafo.o Main.o
LINKOBJ  = Grafo.o Main.o
LIBS     = -L"F:/Archivos de Programa/Dev-Cpp/MinGW64/lib" -L"F:/Archivos de Programa/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"F:/Archivos de Programa/Dev-Cpp/MinGW64/include" -I"F:/Archivos de Programa/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Archivos de Programa/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/Archivos de Programa/Dev-Cpp/MinGW64/include" -I"F:/Archivos de Programa/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Archivos de Programa/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/Archivos de Programa/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = a.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Grafo.o: Grafo.cpp
	$(CPP) -c Grafo.cpp -o Grafo.o $(CXXFLAGS)

Main.o: Main.cpp
	$(CPP) -c Main.cpp -o Main.o $(CXXFLAGS)
